// <auto-generated />
using System;
using Electricad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Electricad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210714104856_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Electricad.Data.About", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("about_desc")
                        .HasColumnType("text");

                    b.Property<string>("about_file")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_about");
                });

            modelBuilder.Entity("Electricad.Data.Offers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("descount")
                        .HasColumnType("int");

                    b.Property<string>("offer_file")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_offers");
                });

            modelBuilder.Entity("Electricad.Data.Portfolio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("port_file")
                        .HasColumnType("text");

                    b.Property<int>("sector_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("tb_portifolio");
                });

            modelBuilder.Entity("Electricad.Data.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<string>("dateComment")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_reviews");
                });

            modelBuilder.Entity("Electricad.Data.Sectors", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Portfolioid")
                        .HasColumnType("int");

                    b.Property<string>("desc")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Portfolioid");

                    b.ToTable("tb_sectors");
                });

            modelBuilder.Entity("Electricad.Data.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Electricad.Data.Portfolio", b =>
                {
                    b.HasOne("Electricad.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electricad.Data.Sectors", b =>
                {
                    b.HasOne("Electricad.Data.Portfolio", null)
                        .WithMany("Sector")
                        .HasForeignKey("Portfolioid");
                });

            modelBuilder.Entity("Electricad.Data.Portfolio", b =>
                {
                    b.Navigation("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
